### ISSUE TITLE
List all accounts that are accessible by the client

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#110]
# Rationale

We need a feature to list all the accounts whose Keystore file is present in the `.razor` folder. This feature is required because the user sometimes might not know which account does he/she has access to and which he/she needs to import.

# Implementation

There is a function, `keystore.Accounts` that lists all the accounts. Just display the account addresses of those accounts. Check [this](https://github.com/razor-network/razor-go/blob/69e7d6b5e4f70bbe330cc6ec952baa7abb1e35a4/accounts/accounts.go#L37) for more details.

**Comment by Yashk767** [comment]
Should I add a command like 'displayAccounts' in order to show the listed accounts ?

**Comment by ashish10677** [comment]
`./razor listAccounts` will be a better option IMO
