### ISSUE TITLE
razor-go crashes on RPC timeout

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#123]
#### System information

- **OS & Version**: Linux
- **Go version:** stable
- **razor-go version:** 0.1.31

#### Describe the bug
When the RPC URL times out, razor-go crashes. This happens on infura quite frequently.

#### Expected behaviour
On RPC errors, do not crash

#### Actual behaviour
razor-go crashes

#### Steps to reproduce the behaviour
1. Run `razor vote`
2. Wait for RPC to crash

**Comment by ashish10677** [comment]
@OxHimanshu can you attach the logs for this issue?

**Comment by OxHimanshu** [comment]
[logs.txt](https://github.com/razor-network/razor-go/files/6975187/logs.txt)
