### ISSUE TITLE
Secret needs to be calculated with chainID

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#129]
# Rationale

The secret could be guessed if we move to a new network and the same epoch repeats.

# Implementation

Create a secret along with the chain ID of the network, and a salt `razororacle`

**Comment by ashish10677** [comment]
There are 2 places wherein we are hashing the values to calculate the secret.
```
func calculateSecret(account types.Account, epoch *big.Int) []byte {
	hash := solsha3.SoliditySHA3([]string{"address", "uint256"}, []interface{}{account.Address, epoch.String()})
	signedData, err := accounts.Sign(hash, account, utils.GetDefaultPath())
	if err != nil {
		log.Error("Error in signing the data: ", err)
		return nil
	}
	secret := solsha3.SoliditySHA3([]string{"string"}, []interface{}{hex.EncodeToString(signedData)})
	return secret
}
```

One is while calculating the `hash` variable and one while calculating the `secret`. Where is the salt and chain Id supposed to be added?

**Comment by SkandaBhat** [comment]
Hash
