### ISSUE TITLE
Store error logs in a file

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#130]
# Rationale

# Implementation

**Comment by SkandaBhat** [comment]
Should have following:
- Network
- Version
- config (provider, gasmultiplier etc)
- OS details (snapshot of memory and storage)
- timestamp

Should be easy to debug a problem using the error log.

**Comment by SkandaBhat** [comment]
Should have output log with:
- all the output of the client
- Similar details as error log

**Comment by ashish10677** [comment]
[This](https://www.honeybadger.io/blog/golang-logging/#:~:text=If%20you%20need%20to%20store,OpenFile(%22logs.) can be used for reference.
