### ISSUE TITLE
Read password from file

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#131]
# Rationale

In servers, we need a way to read account password from a file to make it easier to run vote in an automated way.

# Implementation

Add an argument --password and supply a text file that razor-go can read from.

eg., ./razor vote --address <addr> --password $HOME/password

Contents of $HOME/password:
password of the respective account in the first line. Anything after newline or EOF will be disregarded

**Comment by ashish10677** [comment]
Need a little discussion on the UX for this feature.

**Comment by SkandaBhat** [comment]
Implementation:

Add an argument --password and supply a text file that razor-go can read from.

eg., `./razor vote --address <addr> --password $HOME/password`

Contents of `$HOME/password`:
<password of the respective account in the first line. Anything after newline or EOF will be disregarded>

**Comment by ashish10677** [comment]
This would be applicable for all the commands right?

**Comment by SkandaBhat** [comment]
Correct. Any command that requires password, the user must be able to either supply it in prompt or provide a file.
