### ISSUE TITLE
If staker crashes after commit, they should be able to bring up the node and continue with reveal

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#133]
# Implementation

Store commit data of current epoch in `.razor`. When node is restarted, check for existing commit data, or else start afresh.

**Comment by ashish10677** [comment]
I don't think this is possible, because in commit state we don't send the commitment values to the smart contract. If the staker crashes after commit, the values are lost. There is no way we can retrieve the values and reveal after the crash.

**Comment by SkandaBhat** [comment]
We need to store the state in razor-go storage. Wont that solve the issue? @ashish10677
