### ISSUE TITLE
`addresses.json` doesn't work if we create a binary of razor-go

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#146]
#### System information

- **OS & Version**: MacOS
- **Go version:** go1.16.4 darwin/arm64
- **razor-go version:** v0.1.5

#### Describe the bug
Building the binary with addresses.json doesn't work. It throws an error whenever I want to run any command.

#### Expected behaviour
The binary should work without any errors.

#### Actual behaviour
`razor-go` throws an error.

#### Steps to reproduce the behaviour
1. Deploy the contracts v0.1.5.
2. Get the addresses.json file and paste it at `razor-go/deployed_addresses/`.
3. Build the binary, `npm run build-all`
4. Try to create a job.

#### Backtrace

```
./razor createJob --address 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 -n btcusd_gemini -r true -s last -u https://api.gemini.com/v1/pubticker/btcusd
Password:       
INFO[2021-08-19T17:01:06+05:30] Connected to: http://127.0.0.1:8545          
2021/08/19 17:01:07 open ./../deployed_addresses/addresses.json: no such file or directory
```

**Comment by SkandaBhat** [comment]
I assumed the binary would contain the addresses.json. It seems like it is trying to read from fs itself. This will not work, we need the addresses to be built in the binary for security reasons. @Yashk767 @ashish10677

**Comment by ashish10677** [comment]
> I assumed the binary would contain the addresses.json. It seems like it is trying to read from fs itself. This will not work, we need the addresses to be built in the binary for security reasons. @Yashk767 @ashish10677

Yes precisely.

**Comment by SkandaBhat** [comment]
In that case, will revert the PR associated with this.

**Comment by ashish10677** [comment]
@SkandaBhat what should be done about this issue? I don't think you can bind the JSON file as a part of the binary.
