### ISSUE TITLE
Razor-Go testing Epic

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#186]
- [x] #195
- [x] #199
- [x] #187
- [x] #188
- [x] #191
- [x] #192
- [x] #193
- [x] #194
- [x] #189
- [x] #196
- [x] #197
- [x] #198
- [x] #200
- [x] #201
- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208
- [x] #216
- [x] #303
- [x] #304
- [x] #305
- [x] #368 
- [x] #369
- [x] #370
- [x] #371
- [x] #392
- [x] #393
- [x] #394
- [x] #395
- [x] #396
- [x] #397
- [x] #474
- [x] #475
- [x] #521
- [x] #522
- [x] #523
- [x] #524
- [x] #525
- [x] #545
- [x] #568

**Comment by SkandaBhat** [comment]
Pausing the remaining items.

**Comment by SkandaBhat** [comment]
Resumed.

**Comment by ashish10677** [comment]
Closing this since all the tasks are completed.
