### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#254]
README needs to be updated with the latest changes in the repository.
@OxHimanshu please list down the changes required.

**Comment by OxHimanshu** [comment]
We might need few changes mentioned below:
-  (--logLevel debug) - > check logging while staking
-  (--power) -> Required while creating collections and jobs
-  (--value) -> Replaced amount with value while staking

**Comment by ashish10677** [comment]
Just noticed, that some places, the command description is also outdated, just like the README.
