### ISSUE TITLE
Logger enhancement

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#276]
# Rationale

Right now, we have only one file, razor.log to log all the details of all the stakers running in the same system. This makes it difficult to debug, because we don't know, for which particular staker, at which epoch the error occured.

# Implementation

We can add extra info “staker”, “state”, “epoch” on each line, that will help any log analysis service to filter.

**Comment by SkandaBhat** [comment]
@ashish10677 please keep an eye out for RPC usage, we should ideally not use any more RPC calls while implementing this.

**Comment by SkandaBhat** [comment]
## Implementation
- [ ] Keep a general memory with staker address
- [ ] Update it on user input
- [ ] on every log, fetch staker address and add to log
