### ISSUE TITLE
Commit reverts whenever age is > 70000

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#289]
Not sure about the cause -> effect here. But this pattern seems to be true.

#### System information

- **OS & Version**: Windows/Linux/OSX
- **Go version:** 
- **razor-go version:** 

#### Backtrace

````
[backtrace]
````

**Comment by abhishekvispute** [comment]
hmm this is weird but, how it can underflow if at first we are checking if penalty is larger

**Comment by SamAg19** [comment]
Lets test

> hmm yes I also thought same before But that's not the case Before it reverted age was 69992 And medians were [ 3725, 57483 ] votes were [3725, 57484]
> 
> so if we take worst scenarios it would be prod = 69992*57484 = 4,02,34,20,128 which is smaller than max of uint64 => 18,446,744,073,709,551,616

Lets make use of the scenario testcase for 100 epochs participation but change the medians from 100, 200s with realistic medians like 3725, 57483 and see how it interacts

@SkandaBhat @abhishekvispute

**Comment by SamAg19** [comment]
I earlier ran on 0.1.7 in which i did not experience any error but for 0.1.63, i experienced this error. The error is coming from uint64 prod calculation. This error got fixed though when i changed it to ```uint64 prod = uint64(age) * uint64(voteValueLastEpoch);```

the original result of ```age * voteValueLastEpoch``` is a uint32 which was apparently overflowing. The above change fixed the issue
