### ISSUE TITLE
Dockerfile needs to be updated

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#360]
The docker file doesn't work. It needs to be updated.

#### System information

- **OS & Version**: Windows/Linux/OSX
- **Go version:** 
- **razor-go version:** 

#### Backtrace

````
[backtrace]
````

**Comment by Shrikant1212** [comment]
@ashish10677  can help in reviewing [PR](https://github.com/razor-network/razor-go/pull/362)

**Comment by ashish10677** [comment]
> @ashish10677 can help in reviewing [PR](https://github.com/razor-network/razor-go/pull/362)

Yeah I'll review.
