### ISSUE TITLE
Bug report template doesn't redirect to a valid page in CONTRIBUTE.md

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#41]
The bug report template link should ideally redirect to https://github.com/razor-network/razor-go/issues/new?assignees=&labels=type%3Abug&template=bug.md&title= but it doesn't do so.

**Comment by arin17bishwa** [comment]
would like to take this up

**Comment by ashish10677** [comment]
Sure @arin17bishwa go ahead.

**Comment by arin17bishwa** [comment]
Created PR #42
