### ISSUE TITLE
Setup a testing framework by mocking a blockchain.

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#44]
# Rationale

Currently, to test any issue/feature, it's a very tedious process, to run ganache-cli, then deploy all contracts, create accounts, etc. It would be good if we have a testing framework that does all of this by mocking the blockchain.

# Implementation

[This](https://medium.com/coinmonks/unit-testing-solidity-contracts-on-ethereum-with-go-3cc924091281) can be an inspiration on how to approach this feature.

**Comment by SkandaBhat** [comment]
Not valid anymore.
