### ISSUE TITLE
'make all' to generate bindings gives error but running generate-bindings.sh works.

### ISSUE THREAD

**Issue by Yashk767** [razor-network/razor-go#52]
#### System information

- **OS & Version**: Linux/Ubuntu 20.04.2 LTS
- **Go version:**  go1.16.5 linux/amd64
- **razor-go version:** v1.0.0

#### Describe the bug
- Able to generate bindings by just running generate-bindings.sh , but aiming the same thing to be done by make all gives an error.

#### Expected behaviour
-When running make all ,its expected the bindings to be generated but there's an error in pipefail and Makefile.

#### Actual behaviour
ERROR :
Installing contract dependencies...
generate-bindings.sh: 3: set: Illegal option -o pipefail
make: *** [Makefile:11: fetch_bindings] Error 2

-Tried to fix this by removing the set -e -o pipefail line , there's still an Makefile error which looks quiet strange.

ERROR: 
Installing contract dependencies...

generate-bindings.sh: 16: Syntax error: "(" unexpected
make: *** [Makefile:11: fetch_bindings] Error 2

**Comment by ashish10677** [comment]
Looks like [this](https://askubuntu.com/questions/95365/bash-is-abnormal-in-makefile) might be the issue.

**Comment by Yashk767** [comment]
Resolved, Thanks.
Worked by changing SHELL = /bin/bash in Makefile for Ubuntu.

**Comment by ashish10677** [comment]
Can you raise a PR and change SHELL to /bin/bash permanently. Also in generate-bindings.sh also change it to #!bin/bash

**Comment by Yashk767** [comment]
Sure.
