### ISSUE TITLE
Accounts are getting blocked on Polygon Mumbai

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#549]
We have had 3 instances of accounts getting blocked by polygon testnet miners. When the keystore is imported to metamask, transactions go through.

- [ ] Reproduce this issue on staging
- [ ] Find out if razor-go is behaving in a suspicious way.

Related to [#552](https://github.com/razor-network/razor-go/issues/552)

One hunch I have is the retry mechanism, what is the time duration between retries?

**Comment by ashish10677** [comment]
> One hunch I have is the retry mechanism, what is the time duration between retries?
The time duration is exponentially increasing with every retry: 1 sec, 2 sec, 4sec, 8 sec, 16 sec

**Comment by SkandaBhat** [comment]
Need to check for multiple instances. Retry could be causing problems.

**Comment by SkandaBhat** [comment]
One fix for this would be to check config gasPrice < suggested gasPrice, if so use suggested gasprice.
