### ISSUE TITLE
Jobs override v2

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#561]
Jobs should be overridden in a manner such that:

## The structure of assets.json is something like this:
```
{
  "assets": {
    "collection": {
      "ethCollection": {
        "power": 2,
        "official jobs": {
          "1": {
            "URL": "http://kucoin.com/eth1",
            "selector": "eth1",
            "power": 2,
            "weight": 2
          },
          "2": {
            "URL": "http://api.coinbase.com/eth2",
            "selector": "eth2",
            "power": 3,
            "weight": 2
          }
        },
        "custom jobs": [
          {
            "URL": "http://127.0.0.1/eth1",
            "selector": "eth1",
            "power": 2,
            "weight": 3
          },
          {
            "URL": "http://127.0.0.1/eth2",
            "selector": "eth2",
            "power": 2,
            "weight": 2
          },
          {
            "URL": "http://127.0.0.1/eth3",
            "selector": "eth3",
            "power": 2,
            "weight": 2
          }
        ]
      }
    }
  }
}
```
The custom jobs array will contain all the customs jobs that have to be overridden and razor-go will pick these jobs for the collection.

- [ ] jobs.json renamed to assets.json
- [ ] Check assets.json for a collection, if that collection is present, pull all the data from the official jobs and custom jobs (if it exists)
- [ ] If the power of the collection is mentioned in assets.json, use that power value.
- [ ] Aggregation method however will always be fetched from the smart contract.
- [ ] The override flag will be removed and override will be implicit.

**Comment by Yashk767** [comment]
Found this for getting values from json file https://github.com/tidwall/gjson, makes nested data retrieval easy.
Can we go with this ? @SkandaBhat @ashish10677

**Comment by SkandaBhat** [comment]
Ok

**Comment by SkandaBhat** [comment]
1. Fetch all jobs and collections from contract
2. Iterate thru collections
    1. Iterate thru jobs
    2. Fetch from jobs
        1. Lookup job in assets.json
        2. If job id exists in collection in assets.json in official jobs, use overrided job details, if not, continue
    3. Aggregate
        1. Fetch custom jobs from assets.json and merge with official jobs list
        2. Continue with aggregation
    4. Return to collection
