### ISSUE TITLE
Remove unnecessary files from coveralls.

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#568]
Not all files need to be covered on coveralls. Files not required in coveralls are: 

- [ ] accounts/accountUtils.go
- [ ] cmd/root.go
- [ ] cmd/struct-utils.go
- [ ] path/mocks
- [ ] utils/struct-utils.go

**Comment by Shrikant1212** [comment]
@ashish10677  Can we skip these files while running test or Just need need to remove form coveralls?

**Comment by ashish10677** [comment]
A few more files need to be ignored from coveralls:

- [ ] accounts/accountUtils.go
- [ ] cmd/interface.go
- [ ] cmd/root.go
- [ ] cmd/struct-utils.go
- [ ] path/mocks
- [ ] path/pathUtils.go
- [ ] utils/password.go
- [ ] utils/interface.go
- [ ] utils/struct-utils.go
- [ ] metrics/server.go
