### ISSUE TITLE
SKALE release changes.

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#570]
# Description

- [ ] Update the contract address with those deployed on SKALE
- [ ] Change GetDelayedState function to work with block.timestamp instead of block number.
- [ ] Tweak and change the epochLength and stateLength parameters.

**Comment by SkandaBhat** [comment]
@ashish10677 please add description

**Comment by ashish10677** [comment]
> @ashish10677 please add description

Done @SkandaBhat
