### ISSUE TITLE
Optimisations for razor-go

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#634]
# Rationale
There are a bunch of places where we are using O(n<sup>2</sup>) and we are doing things that can be optimised.
This issue will be used to keep a track of those optimisations.

## List of Optimisations

- [x] In dispute calculation`CheckDisputeForIds` can be optimised by adding a hashing algorithm to test first whether there is any dispute or not. Once we are confirmed whether there is a dispute or not, then we can go ahead and check the type of dispute.
- [ ] `GetIteration` method has to be optimized.

**Comment by ashish10677** [comment]
Please add more points if there are more optimizations.

**Comment by SkandaBhat** [comment]
@ashish10677 has this been picked up?
