### ISSUE TITLE
Benchmark all the loops

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#686]
# Rationale

# Implementation

**Comment by SkandaBhat** [comment]
@Yashk767 has this been picked up?

**Comment by Yashk767** [comment]
cmd package -
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/collectionList.go#L49
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/commit.go#L60
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/dispute.go#L58
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/dispute.go#L316
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/dispute.go#L346
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/jobList.go#L48
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/listAccounts.go#L28
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L188
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L224
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L271
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L293
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L330
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/propose.go#L361
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/reveal.go#L80
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/reveal.go#L130
- [ ] https://github.com/razor-network/razor-go/blob/main/cmd/vote.go#L522

**Comment by Yashk767** [comment]
> @Yashk767 has this been picked up?

Yes I had started but paused it for few days as shifted to other task. Continuing it now.
