### ISSUE TITLE
Improve password policy

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#752]

**Comment by shekhar2807** [comment]
Primary conditions for password validation :

- Minimum 8 characters.
- The alphabets must be between [a-z]
- At least one alphabet should be of Upper Case [A-Z]
- At least 1 number or digit between [0-9].
- At least 1 character from [ _ or @ or $ ].

Is this fine or do you guys have any other idea . Let me know @ashish10677 @SkandaBhat
