### ISSUE TITLE
Docker Image run as root

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#754]
Impact of running container as root and non-root user

- If we run container as root then container have privilege to access host file system.
- If someone(non-root user of our host machine) will get access of our container then user can access privilege files  of our host as well.
- Non-root user of our host machine can access privilege files of our container as well.

Ways to Get access of our container:

- If we have any malicious code as dependency then that code can get access of privilege files of container.
- If someone get access of host, which we can't control

**Comment by Shrikant1212** [comment]
If we create container as non-root user then container will behave different on mac and Linux:

- In MAC as non-root user, if we create/import account or create razor.yaml via cli then those will create files as  non-root user.
- In linux, if we create/import account or create razor.yaml via cli then those will create files as root user of host, so non-root user can't access those.
 
**Suggestion** :
As we are creating keystore and razor.yaml which are sensitive files and those should only be accessible via root user of host so we should use root user to run our container as well and customer should maintain  access of docker cli with proper permission.

It is suggested to run container as root but as we are creating sensitive files, we should store those in `/root` directory of our host machine and that can access via root user only

**Workaround** :

- We can run our container as non-root but we need to update permission of file/directory via `chmod` utility present in linux manually.
-  Customer can create any user host machine and that user should have same id which we mention in our Dockerfile, but if customer already have user with that id then he need to create new container or recreate user in host.
 
**Best way todo**:

- We should check our dependencies 
- Customer should secure docker cli
