### ISSUE TITLE
Rogue mode doesn't work

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#776]

**Comment by SkandaBhat** [comment]
This needs to be reproduced. @Shrikant1212 can you help with reproduction steps?

**Comment by Shrikant1212** [comment]
**Contracts details:**
Branch: `v1-audit-feedback`

Address:
```
{
  "Governance": "0x687D7f19fb152884775ef7B378f225a57621Ee3c",
  "BlockManager": "0xCaFD63826Be59dFCa88Ed974BBc39c97BaF3360A",
  "CollectionManager": "0x16B03bb9Fc60685b10658662e3661736a7bE44a3",
  "StakeManager": "0x5bac88695fc31F47E94E544e46f363C81Ec15788",
  "RewardManager": "0x481936169Df3B1Ae9DB6Eec1Ad7E9e1fb000D280",
  "VoteManager": "0x0Fe4844E54FfB17D21a7957F447956B78E14A384",
  "Delegator": "0xc8D0b3C978FF7D21c19e60E470b958F51Cda4458",
  "RAZOR": "0x7F979d1890BAAC7cd1e87C3B75a00Be5122D69dE",
  "StakedTokenFactory": "0x32D93c88b860663E61B857B559fD0FBC10258Ee9",
  "RandomNoManager": "0x52Cb711FFbFBF3de4EC6A2ee16067888A69B9E16"
}
```


**Razor-go details:**

Branch:  `v1.0.3-incentivised-testnet-phase2-patch2)`
Platform: docker

Build step: `docker build -t razor-go .`
Start cmd: `docker run -d -it --name razor-go -v "$(echo $HOME)":/home/razor  razor-go`
rogue cmd: `docker exec -it razor-go razor vote --address 0x1EbF851e7E1672d88f5eE9E1f5705c67572eb708  --rogue --rogueMode commit,reveal,medians,missingIds,extraIds,unsortedIds`

**Comment by Kaizoku-Shrikant** [comment]
Please use 
Start cmd
`docker run -d -it --name razor-go -v "$(echo $HOME)"/.razor:/root/.razor razor-go`

**Comment by SkandaBhat** [comment]
This has been closed. This was a problem with wrong ABIs.
