### ISSUE TITLE
V1 minor releases setup

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#924]
- [x] Create a Branch v1

- [x] Make the branch protected

- [x] Merge all v1 issues fixes to v1 branch

- [x] Create releases from v1 branch weekly

**Comment by ashish10677** [comment]
@SkandaBhat I don't have the rights to make v1 as a protected branch. Could you please do it?

**Comment by SkandaBhat** [comment]
Done. Closing this. @ashish10677
