### ISSUE TITLE
StakerInfo command not working

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#929]
#### System information

- **OS & Version**: MacOS
- **Go version:** go 1.17
- **razor-go version:** 1.0.0-mainnet stable

#### Describe the bug
`stakerInfo` command isn't working

#### Expected behaviour
`stakerInfo` command should return the staker information of the staker whose staker id is provided

#### Actual behaviour
`stakerInfo` command returns staker id as 0, staker address as 0x00000....00.

#### Steps to reproduce the behaviour
1. Run stakerInfo command on razor-go.

#### Backtrace
![image](https://user-images.githubusercontent.com/27495644/188739340-7cb0fd6f-1704-4d67-b374-fd3c4ecba35d.png)

**Comment by shekhar2807** [comment]
The correct command is: sudo docker exec -it razor-go razor stakerInfo --stakerId 15
