### ISSUE TITLE
[Discussion] Should rogue mode removed completely from razor-go mainnet release?

### ISSUE THREAD

**Issue by ashish10677** [razor-network/razor-go#930]
`razor-go` currently has the option of running in rogue mode. Stakers **SHOULD NOT** try using it, as it will result in monetary loss. Should we completely disable rogue mode in razor-go release?

**Comment by SkandaBhat** [comment]
Should be ok. Stakers are responsible enough to not try it. Do we have a warning message on rogue mode? @ashish10677

**Comment by ashish10677** [comment]
No that's not there. Should I add it in https://github.com/razor-network/razor-go/issues/916 itself?

**Comment by SkandaBhat** [comment]
yeah should be added as part of #916. Closing this.
